#!/usr/bin/env python3
"""inventory.py -- generate reports/regions.md from the current region map.

Lists every decoded code region with its flat address range, the CS value it
is disassembled under, its size, and the named entry points inside it, then
summarises what is left over and how it was classified.

    python3 inventory.py > asm/baseline-2026-09/reports/regions.md
"""
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import grow                                              # noqa: E402


# Gaps that carry a note beyond what the byte statistics can say.  Keyed by
# start address; the note is appended to the classification.
ANNOTATED = {
    0xF5183: "far-pointer table (155 entries) read by `LES SI,CS:52xx/53xx` "
             "in decoded code; 146 of the 155 point into segments "
             "0000/1000/2000/3000, i.e. inside the LMCS window, and 9 into "
             "segment 4000 (work RAM)",
}

FILL_BYTES = (0x00, 0xFF)
MIN_FILL_RUN = 256          # below this a trailing run is not worth splitting


def split_gap(lo, hi, rom):
    """Split one gap into [(start, end, kind)] runs.

    A single dominant-byte test is not enough: a gap can be 99% zero and
    still open with live data.  (F5183..FFF00 is 98.98% zero, yet its first
    620 bytes are a far-pointer table that decoded code reads.)  So trailing
    uniform fill is measured exactly and split off, and whatever precedes it
    is reported as data on its own terms.
    """
    blob = rom[lo - grow.ROM1_BASE:hi - grow.ROM1_BASE]
    if not blob:
        return []
    fill = blob[-1]
    run = 0
    if fill in FILL_BYTES:
        while run < len(blob) and blob[len(blob) - 1 - run] == fill:
            run += 1
    if run == len(blob):
        return [(lo, hi, "unprogrammed (0x%02X fill, verified uniform)" % fill)]
    if run < MIN_FILL_RUN:
        return [(lo, hi, describe(blob, lo))]
    split = hi - run
    return [(lo, split, describe(blob[:len(blob) - run], lo)),
            (split, hi, "unprogrammed (0x%02X fill, verified uniform)" % fill)]


def describe(blob, lo):
    c = Counter(blob)
    top, n = c.most_common(1)[0]
    pct = 100 * n // max(1, len(blob))
    nz = sum(1 for v in blob if v)
    note = "data (%d bytes, %d non-zero, most common byte %02X = %d%%)" % (
        len(blob), nz, top, pct)
    if lo in ANNOTATED:
        note += " -- " + ANNOTATED[lo]
    return note


def main():
    entries, regions, _ = grow.build_regions()
    rom = open(grow.ROM, "rb").read()
    named = {}
    for a, s, l in entries:
        named.setdefault(a, l)

    code = sum(e - s for s, e, _ in regions)
    print("# IO Moon 80188 baseline -- decoded code regions\n")
    print("Generated by `asm/baseline-2026-09/tools/inventory.py`; flat 80188")
    print("addresses, ROM1 file offset = address - 0x80000.\n")
    print("%d regions, %d bytes of decoded code inside the 0x%05X-0x%05X "
          "UMCS window.\n" % (len(regions), code, grow.CODE_LO,
                              grow.CODE_HI - 1))
    print("| region | CS | bytes | named entry points |")
    print("|---|---|---|---|")
    for s, e, g in regions:
        names = [named[a] for a in sorted(named) if s <= a < e
                 and not named[a].startswith("sub_")]
        print("| `%05X..%05X` | `%04X` | %d | %s |"
              % (s, e, g, e - s,
                 ", ".join("`%s`" % n for n in names) if names else
                 "%d unnamed" % sum(1 for a in named if s <= a < e)))

    print("\n## Everything else in the window\n")
    print("| gap | bytes | classification |")
    print("|---|---|---|")
    prev = grow.CODE_LO
    other = 0

    def emit(lo, hi):
        for a, b, kind in split_gap(lo, hi, rom):
            print("| `%05X..%05X` | %d | %s |" % (a, b, b - a, kind))

    for s, e, g in regions:
        if s > prev:
            emit(prev, s)
            other += s - prev
        prev = max(prev, e)
    if prev < grow.CODE_HI:
        emit(prev, grow.CODE_HI)
        other += grow.CODE_HI - prev
    print("\nCode %d bytes, other %d bytes, window %d bytes."
          % (code, other, grow.CODE_HI - grow.CODE_LO))


if __name__ == "__main__":
    main()
