#!/usr/bin/env python3
"""inventory.py -- generate reports/regions.md from the current region map.

Lists every decoded code region with its flat address range, the CS value it
is disassembled under, its size, and the named entry points inside it, then
summarises what is left over and how it was classified.

    python3 inventory.py > asm/baseline-2026-09/reports/regions.md
"""
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import grow                                              # noqa: E402


def classify(lo, hi, rom):
    blob = rom[lo - grow.ROM1_BASE:hi - grow.ROM1_BASE]
    c = Counter(blob)
    top, n = c.most_common(1)[0]
    pct = 100 * n // max(1, len(blob))
    if top == 0xFF and pct > 95:
        return "unprogrammed (0xFF fill)"
    if top == 0x00 and pct > 95:
        return "unprogrammed (0x00 fill)"
    return "data (most common byte %02X = %d%%)" % (top, pct)


def main():
    entries, regions, _ = grow.build_regions()
    rom = open(grow.ROM, "rb").read()
    named = {}
    for a, s, l in entries:
        named.setdefault(a, l)

    code = sum(e - s for s, e, _ in regions)
    print("# IO Moon 80188 baseline -- decoded code regions\n")
    print("Generated by `asm/baseline-2026-09/tools/inventory.py`; flat 80188")
    print("addresses, ROM1 file offset = address - 0x80000.\n")
    print("%d regions, %d bytes of decoded code inside the 0x%05X-0x%05X "
          "UMCS window.\n" % (len(regions), code, grow.CODE_LO,
                              grow.CODE_HI - 1))
    print("| region | CS | bytes | named entry points |")
    print("|---|---|---|---|")
    for s, e, g in regions:
        names = [named[a] for a in sorted(named) if s <= a < e
                 and not named[a].startswith("sub_")]
        print("| `%05X..%05X` | `%04X` | %d | %s |"
              % (s, e, g, e - s,
                 ", ".join("`%s`" % n for n in names) if names else
                 "%d unnamed" % sum(1 for a in named if s <= a < e)))

    print("\n## Everything else in the window\n")
    print("| gap | bytes | classification |")
    print("|---|---|---|")
    prev = grow.CODE_LO
    other = 0
    for s, e, g in regions:
        if s > prev:
            print("| `%05X..%05X` | %d | %s |"
                  % (prev, s, s - prev, classify(prev, s, rom)))
            other += s - prev
        prev = max(prev, e)
    if prev < grow.CODE_HI:
        print("| `%05X..%05X` | %d | %s |"
              % (prev, grow.CODE_HI, grow.CODE_HI - prev,
                 classify(prev, grow.CODE_HI, rom)))
        other += grow.CODE_HI - prev
    print("\nCode %d bytes, other %d bytes, window %d bytes."
          % (code, other, grow.CODE_HI - grow.CODE_LO))


if __name__ == "__main__":
    main()
